### ISSUE TITLE
Update dependency strip-ansi, because of vulnerability

### ISSUE THREAD

**Issue by skaugvoll** [timoxley/columnify#61]
**What:**
Update dependency `strip-ansi` to latest. 
```
 "dependencies": {
    "strip-ansi": "^3.0.0",
```

`strip-ansi` has a vulnerability because it has a dependency to `ansi-regex` version `v<5.0.1`

**Why:**
When using docker image node:16-alpine3.14, columnify is listed as a dependency to npm@8.1.x, and gives an error when using tools such as aquasec/trivy to scan for vulnerabilities

**Comment by psandeep09** [comment]
any update?

**Comment by viceice** [comment]
Looks like this project is dead, no commit since 2018 😕

**Comment by viceice** [comment]
@timoxley Can you please comment? I can open a PR to fix this

**Comment by timoxley** [comment]
Ah apologies. I'll take a look at this tomorrow.

**Comment by bybraveHQ** [comment]
For anyone landing here from `npm audit`: I've published a maintained, drop-in fork — **[@bybrave/columnify2](https://www.npmjs.com/package/@bybrave/columnify2)**.

The advisory's root cause is the dependency chain `columnify → strip-ansi → ansi-regex`. The fork **vendors `wcwidth`, `strip-ansi` and `ansi-regex@5` into the package**, so it has **zero runtime dependencies** and the advisory disappears with the tree — nothing transitive left to flag.

While there I also fixed several long-standing issues and modernized packaging:
- Zero runtime dependencies (this issue)
- Options object no longer mutated / works when frozen (#64)
- No more `RangeError: Maximum call stack size exceeded` on very wide columns (#52)
- Per-column `paddingChr` honored (#47), and ANSI/wide padding chars no longer chopped mid-escape-sequence (#17)
- Dual ESM + CommonJS, built-in TypeScript types (replaces `@types/columnify`, #58)

Output is verified **byte-for-byte identical** to the original against the upstream test fixtures, so it's a drop-in replacement:
```
- const columnify = require('columnify')
+ const columnify = require('@bybrave/columnify2')
```
Source & changelog: https://github.com/bybraveHQ/columnify2
